#!/bin/bash
##PBS -N chain_wp_c1h12_all_nthreads20
##PBS -N chain_wp_xi_upf_mcf_c1h12_all_nthreadstest18
##PBS -N chains_wp_xi_xi2_upf_mcf_c1h12_smallscales
##PBS -N chains_wp_upf_c1h12_smallscales
#PBS -N chains_c1h12_minscales
#PBS -l walltime=1000:00:00
#PBS -l nodes=1:ppn=24
#PBS -m ae
#PBS -o logs/$PBS_JOBNAME.out
#PBS -j oe

cd $PBS_O_WORKDIR
PATH=$PBS_O_PATH
echo $PBS_O_WORKDIR
echo 'starting'
echo -n 'Job is running on node '; cat $PBS_NODEFILE
source ~/miniconda3/etc/profile.d/conda.sh
conda activate aem
#python run_chain.py ../chains/configs/chains_wp_xi_xi2_upf_mcf_c1h12_smallscales.cfg
python run_chain_statset.py 1 12
#python run_chain.py ../chains/configs/chains_wp_c0h0.cfg
#python run_chain.py ../chains/configs/chains_wp_xi_xi2_upf_mcf_c5h52_covemuperf.cfg
#python run_chain.py ../chains/configs/chains_wp_xi_upf_mcf_xi2_c3h3.cfg
#python run_chain.py ../chains/configs/chains_wp_xi_xi2_c1h12_covsg1.cfg
#python run_chain.py ../chains/configs/chains_wp_xi_upf_mcf_c1h12_covsg1_nthreadstest.cfg
#mprof run -C python run_chain.py ../chains/configs/chains_wp_c1h12_covsg1_nthreads12.cfg
#python -m memory_profiler run_chain.py ../chains/configs/chains_wp_xi_upf_mcf_c1h12_covsg1.cfg
#mprof run -C python run_chain.py ../chains/configs/chains_wp_xi_upf_mcf_xi2_c1h12_covsg1.cfg
echo 'done'

