#!/bin/bash
##PBS -N chain_wp_aemulus_Msatmocks_test_c3h3
#PBS -N chain_uchuu_wp_xi_xi2_upf_mcf_Msatmocks_upfmaxscale6_covglamsmooth_boundsingle_uchuuchi2nclosest2000
#PBS -l walltime=1000:00:00
#PBS -l nodes=1:ppn=24
#PBS -m ae
#PBS -o logs/$PBS_JOBNAME.out
#PBS -j oe


#cd $PBS_O_WORKDIR
PATH=$PBS_O_PATH
#echo $PBS_O_WORKDIR
echo 'starting'
echo -n 'Job is running on node '; cat $PBS_NODEFILE

# Make sure any symbolic links are resolved to absolute path
#export PBS_O_WORKDIR=$(readlink -f $PBS_O_WORKDIR)  
#export ~/aemulator/chains/results=$(readlink -f ~/aemulator/chains/results)
PBS_O_WORKDIR_MOD=$PBS_O_WORKDIR/..
echo $PBS_O_WORKDIR
echo Running in $PBS_O_WORKDIR_MOD
export PBS_O_WORKDIR_MOD=$(readlink -f $PBS_O_WORKDIR_MOD)
echo Running in $PBS_O_WORKDIR_MOD
cd $PBS_O_WORKDIR

source ~/miniconda3/etc/profile.d/conda.sh
conda activate aem
#python run_chain.py ../chains/configs/chains_wp_xi_xi2_upf_mcf_c4h42_covemuperf.cfg
#python run_chain.py ../chains/configs/chains_wp_aemulus_Msatmocks_test_c3h3.cfg
#python run_chain_statset_singles.py 1 12
#python run_chain_mock.py ../chains/configs/chains_wp80_xi_xi2_upf_mcf_uchuu_wpmaxscale6.cfg
#python run_chain_mock.py ../chains/configs/chains_wp_xi_xi2_upf_mcf_uchuu_Msatmocks_wpmaxscale6.cfg
python run_chain_mock.py ../chains/configs/chains_wp_xi_xi2_upf_mcf_uchuu_Msatmocks_upfmaxscale6_covglamsmooth_boundsingle_uchuuchi2nclosest2000.cfg
#mprof run -C python run_chain.py ../chains/configs/chains_wp_c1h12_covsg1_nthreads12.cfg
#python -m memory_profiler run_chain.py ../chains/configs/chains_wp_xi_upf_mcf_c1h12_covsg1.cfg
#mprof run -C python run_chain.py ../chains/configs/chains_wp_xi_upf_mcf_xi2_c1h12_covsg1.cfg
echo 'done'

