#!/bin/bash
##PBS -N chain_upf_aemulus_fmaxmocks_test_c0h0_maxscale0
##PBS -N chains_xi_xi2_aemulus_fmaxmocks_test_c0h0_fixgammaf_minscale0.cfg
##PBS -N chain_statset_singles_c1h12
##PBS -N chain_uchuu_wp_xi_xi2_upf_mcf_Msatmocks_upfmaxscale6_covglamsmooth_boundsingle_uchuuchi2nclosest2000
##PBS -N chain_wp_xi_xi2_upf_mcf_uchuu_aemulus_fmaxmocks_wpximaxscale6_covnegfix_uchuuchi2nclosest2000
##PBS -N chain_upf_uchuu_aemulus_fmaxmocks_wpximaxscale6_uchuuchi2nclosest2000
##PBS -N chains_wp_xi_xi2_uchuu_aemulus_fmaxmocks_uchuuchi2nclosest2000_smoothboth_wpximaxscale6
##PBS -N chains_wp_xi_xi2_upf_mcf_uchuu_fixgammaf_aemulus_fmaxmocks_uchuuchi2nclosest2000_smoothboth_wpxiupfmaxscale6
##PBS -N chain_wp_xi_xi2_upf_mcf_uchuu_aemulus_fmaxmocks_inflateupferr3nox
##PBS -N chains_wp_xi_xi3_upf_mcf_uchuu_fixgammaf_aemulus_fmaxmocks_smoothboth_allmaxscale6
##PBS -N chains_wp_xi_xi2_uchuu_fixgammaf_aemulus_fmaxmocks_uchuuchi2nclosest2000_smoothemu_wpximaxscale6
#PBS -N chain_c6h66_covemuperf
#PBS -l walltime=1000:00:00
#PBS -l nodes=1:ppn=24
#PBS -m ae
#PBS -o logs/$PBS_JOBNAME.out
#PBS -j oe


#cd $PBS_O_WORKDIR
PATH=$PBS_O_PATH
#echo $PBS_O_WORKDIR
echo 'starting'
echo -n 'Job is running on node '; cat $PBS_NODEFILE

# Make sure any symbolic links are resolved to absolute path
#export PBS_O_WORKDIR=$(readlink -f $PBS_O_WORKDIR)  
#export ~/aemulator/chains/results=$(readlink -f ~/aemulator/chains/results)
PBS_O_WORKDIR_MOD=$PBS_O_WORKDIR/..
echo $PBS_O_WORKDIR
echo Running in $PBS_O_WORKDIR_MOD
export PBS_O_WORKDIR_MOD=$(readlink -f $PBS_O_WORKDIR_MOD)
echo Running in $PBS_O_WORKDIR_MOD
cd $PBS_O_WORKDIR

source ~/miniconda3/etc/profile.d/conda.sh
conda activate aem
python run_chain.py /home/users/ksf293/aemulator/chains/configs/chains_wp_xi_xi2_upf_mcf_aemulus_fmaxmocks_test_c6h66_minscale0_covemuperf.cfg
#python run_chain.py /home/users/ksf293/aemulator/chains/configs/chains_upf_aemulus_fmaxmocks_test_c2h20_maxscale0.cfg
#python run_chain.py /home/users/ksf293/aemulator/chains/configs/chains_wp_xi_xi2_mcf_aemulus_fmaxmocks_test_c0h1_minscale1.cfg
#python run_chain_mock.py /home/users/ksf293/aemulator/chains/configs/chains_wp_xi_xi2_upf_mcf_uchuu_fixgammaf_aemulus_fmaxmocks_uchuuchi2nclosest2000_smoothemu_wpxiupfmaxscale6.cfg
#python run_chain_mock.py /home/users/ksf293/aemulator/chains/configs/chains_wp_xi_xi2_upf_mcf_uchuu_fixgammaf_aemulus_fmaxmocks_smoothboth_allmaxscale6.cfg
#python run_chain_mock.py /home/users/ksf293/aemulator/chains/configs/chains_wp_xi_xi2_upf_mcf_uchuu_fixgammaf_aemulus_fmaxmocks_uchuuchi2nclosest2000_smoothboth_wpxiupfmaxscale6.cfg
#python run_chain.py ../chains/configs/chains_wp_xi_xi2_upf_mcf_c4h42_covemuperf.cfg
#python run_chain.py ../chains/configs/chains_wp_aemulus_Msatmocks_test_c3h3.cfg
#python run_chain_statset_singles.py 1 12
#python run_chain.py ../chains/configs/chains_wp_aemulus_fmaxmocks_test_c0h0_minscale0_wpmaxscale6.cfg
#python run_chain.py ../chains/configs/chains_xi_xi2_aemulus_fmaxmocks_test_c0h0_fixgammaf_minscale0.cfg
#python run_chain.py ../chains/configs/chains_upf_aemulus_fmaxmocks_test_c0h0_maxscale0.cfg
#python run_chain_mock.py ../chains/configs/chains_wp80_xi_xi2_upf_mcf_uchuu_wpmaxscale6.cfg
#python run_chain_mock.py ../chains/configs/chains_wp_xi_xi2_upf_mcf_uchuu_Msatmocks_wpmaxscale6.cfg
#python run_chain_mock.py ../chains/configs/chains_wp_xi_xi2_upf_mcf_uchuu_Msatmocks_upfmaxscale6_covglamsmooth_boundsingle_uchuuchi2nclosest2000.cfg
#python run_chain_mock.py /home/users/ksf293/aemulator/chains/configs/chains_wp_xi_xi2_upf_uchuu_aemulus_fmaxmocks.cfg
#python run_chain_mock.py /home/users/ksf293/aemulator/chains/configs/chains_wp_xi_xi2_upf_mcf_uchuu_aemulus_fmaxmocks_uchuuchi2nclosest2000_covnegfix_wpximaxscale6.cfg
#python run_chain_mock.py /home/users/ksf293/aemulator/chains/configs/chains_upf_uchuu_aemulus_fmaxmocks_uchuuchi2nclosest2000_wpximaxscale6.cfg
#python run_chain_mock.py /home/users/ksf293/aemulator/chains/configs/chains_wp_xi_xi2_upf_mcf_uchuu_aemulus_fmaxmocks_inflateupferr3nox.cfg
#mprof run -C python run_chain.py ../chains/configs/chains_wp_c1h12_covsg1_nthreads12.cfg
#python -m memory_profiler run_chain.py ../chains/configs/chains_wp_xi_upf_mcf_c1h12_covsg1.cfg
#mprof run -C python run_chain.py ../chains/configs/chains_wp_xi_upf_mcf_xi2_c1h12_covsg1.cfg
echo 'done'

