#!/bin/sh
#PBS -N chain_wp
#PBS -l nodes=1:ppn=24

#PBS -t 0-20%4

#PBS -o output/$PBS_JOBNAME.out
#PBS -j oe
  
#cd $PBS_O_WORKDIR
echo $PBS_O_WORKDIR
cd /home/users/ksf293/emulator/code
echo $PBS_O_WORKDIR

echo "Hello from $PBS_ARRAYID..."
declare -i cosmo #need to declare variables to do arithmetic
declare -i hoddigit
declare -i hod
declare -i ncosmos

ncosmos=7
hoddigit=${PBS_ARRAYID}/ncosmos
cosmo=${PBS_ARRAYID}%ncosmos
hod=cosmo*10+hoddigit

stat_str="wp_xi"
echo "Running chain from config file chains_${stat_str}_c${cosmo}h${hod}.cfg"

python run_chain.py ../chains/configs/chains_${stat_str}_c${cosmo}h${hod}.cfg
