#!/bin/sh
##PBS -N recovery70_chains_statset_addin_wpmaxscale6
##PBS -N recovery70_chains_statset_addin_wpximaxscale6
##PBS -N recovery70_chains_statset_singles_maxscale6
##PBS -N recovery70_chains_statset_fixgammaf
##PBS -N recovery70_chains_statset_minscales_wp_xi_xi2_mcf
##PBS -N recovery70_chains_statset_minscale0_wp_xi_xi2_mcf
#PBS -N recovery70_chains_statset_maxscales_remaining
# 1 full node for each chain
#PBS -l nodes=1:ppn=24
# test:
##PBS -t 0-0%1
# full recovery suite of 70; number after % is number of nodes to use
##PBS -t 0-69%6
#PBS -t 0-2%3

#PBS -o logs/$PBS_JOBNAME.out
#PBS -j oe


cd $PBS_O_WORKDIR
PATH=$PBS_O_PATH
echo $PBS_O_WORKDIR
echo 'starting'
echo -n 'Job is running on node '; cat $PBS_NODEFILE
echo "Hello from PBS_ARRAYID $PBS_ARRAYID..."

declare -i cosmo #need to declare variables to do arithmetic
declare -i hoddigit
declare -i hod
declare -i ncosmos

ncosmos=7
hoddigit=${PBS_ARRAYID}/ncosmos
cosmo=${PBS_ARRAYID}%ncosmos
hod=cosmo*10+hoddigit

echo "Running chain set for cosmo $cosmo, hod $hod"

source ~/miniconda3/etc/profile.d/conda.sh
conda activate aem

#python run_chain_statset.py $cosmo $hod single _minscale0
#python run_chain_statset.py $cosmo $hod single _minscale0_wpximaxscale6
#python run_chain_statset_singles.py $cosmo $hod single _maxscale6
#python run_chain_statset_singles.py $cosmo $hod single _minscale0 _fixgammaf
#python run_chain_statset_minscales.py $cosmo $hod minscales
python run_chain_statset_maxscales.py $cosmo $hod maxscales
