#!/bin/sh
#PBS -N recovery700_chain_wp
#PBS -l nodes=1:ppn=24
# test:
##PBS -t 0-0%1
# full recovery suite of 700 (non-unique HODs); number after % is number of nodes to use
##PBS -t 0-699%8
#PBS -t 70-83%8

#PBS -o logs/$PBS_JOBNAME.out
#PBS -j oe

stat_str="wp"

cd $PBS_O_WORKDIR
PATH=$PBS_O_PATH
echo $PBS_O_WORKDIR
echo 'starting'
echo -n 'Job is running on node '; cat $PBS_NODEFILE
echo "Hello from PBS_ARRAYID $PBS_ARRAYID..."

declare -i cosmo #need to declare variables to do arithmetic
declare -i hod
declare -i ncosmos

ncosmos=7
hod=${PBS_ARRAYID}/ncosmos
cosmo=${PBS_ARRAYID}%ncosmos

echo "Running chain from config file chains_${stat_str}_c${cosmo}h${hod}_minscale0.cfg"

source ~/miniconda3/etc/profile.d/conda.sh
conda activate aem

python run_chain.py ../chains/configs/chains_${stat_str}_c${cosmo}h${hod}_minscale0.cfg
